services:
  api:
    build: .
    container_name: api-dev
    ports:
      - '3000:3000'
    depends_on:
      - redis

  prometheus:
    image: prom/prometheus:v2.45.0
    container_name: prometheus-dev
    ports:
      - '9090:9090'
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    depends_on:
      - api
      - node-exporter
      - redis-exporter
      - postgres-exporter

  grafana:
    image: grafana/grafana:latest
    container_name: grafana-dev
    ports:
      - '3001:3000'
    volumes:
      - grafana-data:/var/lib/grafana
      - ./grafana/provisioning/datasources:/etc/grafana/provisioning/datasources
      - ./grafana/provisioning/dashboards:/etc/grafana/provisioning/dashboards
    depends_on:
      - prometheus

  redis:
    image: redis:7
    container_name: redis-dev
    ports:
      - '6379:6379'

  node-exporter:
    image: prom/node-exporter
    container_name: node-exporter-dev
    ports:
      - '9100:9100'

  redis-exporter:
    image: oliver006/redis_exporter
    container_name: redis-exporter-dev
    environment:
      - 'REDIS_ADDR=redis:6379'
    depends_on:
      - redis

  postgres-exporter:
    image: prometheuscommunity/postgres-exporter
    container_name: postgres-exporter-dev
    environment:
      - 'DATA_SOURCE_NAME=postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/postgres?sslmode=disable'

volumes:
  grafana-data:
