# prometheus.yml
global:
  scrape_interval: 10s

scrape_configs:
  - job_name: 'api'
    static_configs: [{ targets: ['api:3000'] }]
    metrics_path: /metrics
  - job_name: 'worker'
    static_configs: [{ targets: ['worker:3000'] }] # 워커도 /metrics 노출 권장
  - job_name: 'node'
    static_configs: [{ targets: ['host.docker.internal:9100'] }] # node-exporter
  - job_name: 'redis'
    static_configs: [{ targets: ['redis-exporter:9121'] }]
  - job_name: 'postgres'
    static_configs: [{ targets: ['postgres-exporter:9187'] }]

# 라벨·타임시리즈 다이어트(예: route에 동적 ID가 섞일 때)
# scrape_configs: relabel_configs로 path 정규화(선택)

rule_files:
  - prometheus-rules/recording.yml
  - prometheus-rules/alerts.yml
