# prometheus.yml
global:
  scrape_interval: 10s

scrape_configs:
  - job_name: 'api'
    static_configs: [{ targets: ['api:3000'] }]
    metrics_path: /metrics
  - job_name: 'node'
    static_configs: [{ targets: ['node-exporter:9100'] }]
  - job_name: 'redis'
    static_configs: [{ targets: ['redis-exporter:9121'] }]
  - job_name: 'postgres'
    static_configs: [{ targets: ['postgres-exporter:9187'] }]

rule_files:
  - prometheus-rules/recording.yml
  - prometheus-rules/alerts.yml
